[build]
  functions = "functions"

[[redirects]]
  from = "/demo"
  to = "/docs/getting-started/get-started.html"
  status = 301
  force = true

[[redirects]]
  from = "/samples/lc-dashboard"
  to = "https://trade-finance-dashboard.kekker.com/"
  status = 301
  force = true

  
